# Generated by Django 2.2.8 on 2020-01-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hubinfo',
            fields=[
                ('hubid', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('dateofbirth', models.DateField(blank=True, default=None, null=True)),
                ('hubid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.hubinfo')),
            ],
        ),
    ]
